create table students (
	id INT,
	name VARCHAR(50),
	age INT,
	country VARCHAR(50)
);
insert into students (id, name, age, country) values (1, 'Fletch', 15, 'South Africa');
insert into students (id, name, age, country) values (2, 'Linn', 85, 'Japan');
insert into students (id, name, age, country) values (3, 'Byrom', 96, 'Germany');
insert into students (id, name, age, country) values (4, 'Jedidiah', 68, 'Moldova');
insert into students (id, name, age, country) values (5, 'Leopold', 52, 'Zimbabwe');
insert into students (id, name, age, country) values (6, 'Saunder', 33, 'China');
insert into students (id, name, age, country) values (7, 'Ardene', 25, 'Portugal');
insert into students (id, name, age, country) values (8, 'Tiffy', 9, 'Indonesia');
insert into students (id, name, age, country) values (9, 'Emmett', 7, 'Indonesia');
insert into students (id, name, age, country) values (10, 'Maryrose', 23, 'Israel');
insert into students (id, name, age, country) values (11, 'Kirbee', 50, 'Mongolia');
insert into students (id, name, age, country) values (12, 'Stacee', 86, 'Brazil');
insert into students (id, name, age, country) values (13, 'Emmalyn', 30, 'Colombia');
insert into students (id, name, age, country) values (14, 'Mauricio', 5, 'Russia');
insert into students (id, name, age, country) values (15, 'Stanislaw', 9, 'China');
insert into students (id, name, age, country) values (16, 'Nessie', 55, 'China');
insert into students (id, name, age, country) values (17, 'Rene', 56, 'Thailand');
insert into students (id, name, age, country) values (18, 'Bailey', 72, 'China');
insert into students (id, name, age, country) values (19, 'Fletcher', 78, 'United States');
insert into students (id, name, age, country) values (20, 'Arri', 65, 'China');
insert into students (id, name, age, country) values (21, 'Rudy', 6, 'Botswana');
insert into students (id, name, age, country) values (22, 'Amelina', 84, 'Bulgaria');
insert into students (id, name, age, country) values (23, 'Constantine', 98, 'New Caledonia');
insert into students (id, name, age, country) values (24, 'Darya', 40, 'Czech Republic');
insert into students (id, name, age, country) values (25, 'Faber', 4, 'Nigeria');
insert into students (id, name, age, country) values (26, 'Loni', 36, 'United States');
insert into students (id, name, age, country) values (27, 'Farrah', 70, 'Indonesia');
insert into students (id, name, age, country) values (28, 'Aliza', 8, 'China');
insert into students (id, name, age, country) values (29, 'Crosby', 41, 'Bulgaria');
insert into students (id, name, age, country) values (30, 'Augustine', 59, 'France');
insert into students (id, name, age, country) values (31, 'Chet', 82, 'Philippines');
insert into students (id, name, age, country) values (32, 'Simonne', 78, 'Brazil');
insert into students (id, name, age, country) values (33, 'Solly', 3, 'Brazil');
insert into students (id, name, age, country) values (34, 'Stesha', 23, 'Philippines');
insert into students (id, name, age, country) values (35, 'Aloisia', 29, 'Czech Republic');
insert into students (id, name, age, country) values (36, 'Wyatt', 91, 'Haiti');
insert into students (id, name, age, country) values (37, 'Kirsti', 27, 'Portugal');
insert into students (id, name, age, country) values (38, 'Silvano', 4, 'Honduras');
insert into students (id, name, age, country) values (39, 'Cirillo', 11, 'Nepal');
insert into students (id, name, age, country) values (40, 'Silvain', 78, 'Ukraine');
insert into students (id, name, age, country) values (41, 'Amata', 84, 'China');
insert into students (id, name, age, country) values (42, 'Chrissie', 20, 'Indonesia');
insert into students (id, name, age, country) values (43, 'Pavel', 96, 'Namibia');
insert into students (id, name, age, country) values (44, 'Nissa', 97, 'Honduras');
insert into students (id, name, age, country) values (45, 'Chrissie', 55, 'Colombia');
insert into students (id, name, age, country) values (46, 'Ricoriki', 74, 'Poland');
insert into students (id, name, age, country) values (47, 'Salomon', 8, 'Argentina');
insert into students (id, name, age, country) values (48, 'Diarmid', 6, 'Brazil');
insert into students (id, name, age, country) values (49, 'Frannie', 53, 'Philippines');
insert into students (id, name, age, country) values (50, 'Meryl', 40, 'France');
insert into students (id, name, age, country) values (51, 'Kessia', 53, 'Ivory Coast');
insert into students (id, name, age, country) values (52, 'Krystalle', 69, 'Brazil');
insert into students (id, name, age, country) values (53, 'Nickolai', 9, 'China');
insert into students (id, name, age, country) values (54, 'Derril', 4, 'Iceland');
insert into students (id, name, age, country) values (55, 'Lawrence', 8, 'Serbia');
insert into students (id, name, age, country) values (56, 'Nealy', 2, 'Brazil');
insert into students (id, name, age, country) values (57, 'Monique', 34, 'France');
insert into students (id, name, age, country) values (58, 'Pietra', 50, 'Guatemala');
insert into students (id, name, age, country) values (59, 'Noel', 56, 'France');
insert into students (id, name, age, country) values (60, 'Anita', 68, 'Indonesia');
insert into students (id, name, age, country) values (61, 'Paola', 69, 'Philippines');
insert into students (id, name, age, country) values (62, 'Tanney', 15, 'China');
insert into students (id, name, age, country) values (63, 'Rooney', 61, 'Sweden');
insert into students (id, name, age, country) values (64, 'Marchelle', 55, 'Indonesia');
insert into students (id, name, age, country) values (65, 'Roxanna', 66, 'Poland');
insert into students (id, name, age, country) values (66, 'Keefe', 86, 'Greece');
insert into students (id, name, age, country) values (67, 'Torin', 55, 'Russia');
insert into students (id, name, age, country) values (68, 'Martino', 3, 'Sierra Leone');
insert into students (id, name, age, country) values (69, 'Nathalie', 54, 'Philippines');
insert into students (id, name, age, country) values (70, 'Lynnelle', 55, 'Indonesia');
insert into students (id, name, age, country) values (71, 'Allister', 53, 'China');
insert into students (id, name, age, country) values (72, 'Randolph', 94, 'Philippines');
insert into students (id, name, age, country) values (73, 'Sally', 13, 'China');
insert into students (id, name, age, country) values (74, 'Malinde', 44, 'Argentina');
insert into students (id, name, age, country) values (75, 'Abra', 54, 'China');
insert into students (id, name, age, country) values (76, 'Erich', 78, 'China');
insert into students (id, name, age, country) values (77, 'Ysabel', 51, 'Russia');
insert into students (id, name, age, country) values (78, 'Gabriella', 30, 'Afghanistan');
insert into students (id, name, age, country) values (79, 'Rodolph', 74, 'Bangladesh');
insert into students (id, name, age, country) values (80, 'Mada', 83, 'Peru');
insert into students (id, name, age, country) values (81, 'Saudra', 99, 'Uzbekistan');
insert into students (id, name, age, country) values (82, 'Catharine', 3, 'Tajikistan');
insert into students (id, name, age, country) values (83, 'Josh', 89, 'Mexico');
insert into students (id, name, age, country) values (84, 'Marisa', 32, 'China');
insert into students (id, name, age, country) values (85, 'Aubrey', 15, 'China');
insert into students (id, name, age, country) values (86, 'Joscelin', 71, 'United States');
insert into students (id, name, age, country) values (87, 'Essy', 44, 'Belarus');
insert into students (id, name, age, country) values (88, 'Jeremias', 100, 'Indonesia');
insert into students (id, name, age, country) values (89, 'Clare', 40, 'Philippines');
insert into students (id, name, age, country) values (90, 'Alic', 10, 'Russia');
insert into students (id, name, age, country) values (91, 'Chrissy', 27, 'Ukraine');
insert into students (id, name, age, country) values (92, 'Brooks', 87, 'Indonesia');
insert into students (id, name, age, country) values (93, 'Trudey', 22, 'Ukraine');
insert into students (id, name, age, country) values (94, 'Elnar', 41, 'China');
insert into students (id, name, age, country) values (95, 'Wynne', 27, 'Ukraine');
insert into students (id, name, age, country) values (96, 'Dulcea', 97, 'Indonesia');
insert into students (id, name, age, country) values (97, 'Paule', 94, 'Russia');
insert into students (id, name, age, country) values (98, 'Prudy', 30, 'Indonesia');
insert into students (id, name, age, country) values (99, 'Francisca', 27, 'France');
insert into students (id, name, age, country) values (100, 'Maynord', 18, 'Brazil');
